version: "3"

services:
  api-transaction:
    hostname: api-transaction
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./transaction_service:/sanic/transaction_service
    command: "poetry run python server.py"
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always
    networks:
      - local-network

  mongodb:
    hostname: mongodb
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  mongodata:
