version: "3"

services:
  api-account:
    hostname: api-account
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/sanic/
    command: "poetry run python server.py"
    env_file:
      - .env
    restart: always
