name: pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 ./ \
        --exclude src/tests \
        --max-line-length 100 \
        --statistics
      
    - name: Discord Webhook Action
      if: ${{ always() }}
      uses: ErnaneJ/action-discord-alerts@main
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}     
        status: ${{ job.status }}
  
  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Analysing the code with bandit
      run: |
        bandit --verbose -r ./
    
    - name: Discord Webhook Action
      if: ${{ always() }}
      uses: ErnaneJ/action-discord-alerts@main
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}     
        status: ${{ job.status }}
